### ISSUE TITLE
Running instruction not working

### ISSUE THREAD

**Issue by brlin-tw** [hallyn/uidmapviz#1]
As a regular user not familiar with Go development I found [the instructions in the running section of the README](https://github.com/hallyn/uidmapviz#running) confusing as running either the `go run mapviz` and `go build` commands do not work:

```
# git clone --depth=1 https://github.com/hallyn/uidmapviz.git
...stripped...
# cd uidmapviz
# apt install -y golang-go
...stripped...
# go run mapviz 
package mapviz is not in GOROOT (/usr/lib/go-1.18/src/mapviz)
# go build
go: cannot find main module, but found .git/config in /root/uidmapviz
	to create a module there, run:
	go mod init
```

I'm running the commands in a Ubuntu 22.04 LXC container, on a Proxmox VE 7.2 bare-metal host.  Any help are appreciated.

**Comment by hallyn** [comment]
Yeah, this project pre-dated go modules.  I made a few updates and was able to run it again locally.
